### ISSUE TITLE
[BUG] Null check operator used on a null value

### ISSUE THREAD

**Issue by VeArnold** [YehudaKremer/msix#126]
### :information_source: Info

**Version: `msix-3.6.0`**

### :speech_balloon: Description

Can not successfully build an unsigned package with version 3.6.0 of the tool.

a) I want to run the `flutter build windows` step separately, thus I added the `--build-windows` false flag
b) The CI/CD pipeline gets stuck at the prompt to install the certificate, so I added the `--install-certificate` flag
c) As I just want an unsigned package, I added the `--sign-msix` flag

However, this results in the following traceback:
```
PS C:\Users\builder\clone> flutter.BAT pub run msix:create --build-windows false --sign-msix false --install-certificate false                   
building msix files...                 -Unhandled exception:                                                                                     
Null check operator used on a null value                                                                                                         
#0      AppxManifest.generateAppxManifest (package:msix/src/appx_manifest.dart:39:45)                                                            
#1      Msix._buildMsixFiles (package:msix/msix.dart:118:26)                                                                                     
<asynchronous suspension>                                                                                                                        
#2      Msix._createMsix (package:msix/msix.dart:100:5)                                                                                          
<asynchronous suspension>                                                                                                                        
#3      Msix.create (package:msix/msix.dart:58:5)                                                                                                
<asynchronous suspension>                                                                                                                        
#4      main (file:///C:/Users/builder/programs/flutter/.pub-cache/hosted/pub.dartlang.org/msix-3.6.0/bin/create.dart:4:3)   
```

Note that the same happens with my old project (which used to work), and also a totally clean new Windows Flutter project. In addition, also happens if I just use:
`flutter.BAT pub run msix:create --build-windows false --sign-msix false`

### :scroll: Pubspec.yaml

Attached is the very basic Pubspec file. 
                                                                                                 
```
name: ios_pingviin                                                                                                                               
description: Test project                                                                                                         
                                                            
publish_to: "none"                                                                     
version: 1.0.0+1                                                                                                                                 
                                                                                                                                                 
environment:                                                                                                                                     
  sdk: ">=2.12.0 <3.0.0"                                                                                                                         
                                                                                                                                                 
dependencies:                                                                                                                                    
  flutter:                                                                                                                                       
    sdk: flutter                                                                                                                                 
                                                                                                                                                                                                                              
  cupertino_icons: ^1.0.2                                                                                                                        
  sklite: ^0.0.1                                                                                                                                 
  msix: ^3.6.0                                                                                                                                   
                                                                                                                                                 
dev_dependencies:                                                                                                                                
  dart_code_metrics: ^4.1.0                                                                                                                      
  flutter_test:                                                                                                                                  
    sdk: flutter                                                                                                                                 
                                                                                                                                                                                                                                         
flutter:                                                                                                                                                                                                                                                 
  uses-material-design: true   
```
