### ISSUE TITLE
[BUG] certificate password in command-line argument not correct

### ISSUE THREAD

**Issue by Vios276** [YehudaKremer/msix#132]
### :information_source: Info

**Version: `3.6.2`**

### :speech_balloon: Description

When i use Command-line argument to run msix:create, certificate password is not correct. it can not contain Exclamation mark.

but i use pubspec.yaml not command-line argument, it worked.

```
flutter pub run msix:create -v --signtool-options /f D:\Project\certificate\naeilsg.com\naeilsg.com.pfx /p 1234!
[  +60 ms] executing: [D:\Project\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +242 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] ee4e09cce01d6f2d7f4baebd247fde02e5008851
[        ] executing: [D:\Project\flutter/] git tag --points-at ee4e09cce01d6f2d7f4baebd247fde02e5008851
[  +53 ms] Exit code 0 from: git tag --points-at ee4e09cce01d6f2d7f4baebd247fde02e5008851
[        ] 3.0.0
[   +6 ms] executing: [D:\Project\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +40 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/stable
[        ] executing: [D:\Project\flutter/] git ls-remote --get-url origin
[  +37 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +104 ms] executing: [D:\Project\flutter/] git rev-parse --abbrev-ref HEAD
[  +43 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] stable
[  +67 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +3 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +41 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[        ] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +60 ms] Using D:\Project\flutter\.pub-cache for the pub cache.
[        ] executing: D:\Project\flutter\bin\cache\dart-sdk\bin\dart __deprecated_pub run msix:create -v --signtool-options /f D:\Project\certificate\naeilsg.com\naeilsg.com.pfx /p 1234
[     0.014s] parsing cli arguments
[     0.137s] validating config values
[     0.141s] running "flutter build windows"...
[    41.130s] building msix files...
[    41.131s] validating build files
[    41.140s] cleaning temporary files
[    41.149s] create app icons
[    41.154s] generating icons
[    43.067s] copying VC libraries
[    43.085s] getting certificate publisher
Unhandled exception:
FormatException: Invalid UTF-8 byte (at offset 14)
#0      _Utf8Decoder.convertChunked (dart:convert-patch/convert_patch.dart:1859:7)
#1      _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:314:28)
#2      _Utf8ConversionSink.add (dart:convert/string_conversion.dart:310:5)
#3      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:72:18)
#4      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#5      _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
#6      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#7      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#8      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#9      _StreamController._add (dart:async/stream_controller.dart:648:7)
#10     _StreamController.add (dart:async/stream_controller.dart:596:5)
#11     _Socket._onData (dart:io-patch/socket_patch.dart:2314:41)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1618:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#16     _StreamController._add (dart:async/stream_controller.dart:648:7)
#17     _StreamController.add (dart:async/stream_controller.dart:596:5)
#18     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1839:33)
#19     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1322:14)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:122:13)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:193:5)
[+47903 ms] "flutter run" took 48,032ms.
[   +4 ms] pub finished with exit code 255
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      _DefaultPub.interactively (package:flutter_tools/src/dart/pub.dart:416:7)
           <asynchronous suspension>
           #2      PackagesForwardCommand.runCommand (package:flutter_tools/src/commands/packages.dart:251:5)
           <asynchronous suspension>
           #3      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1183:27)
           <asynchronous suspension>
           #4      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #5      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #6      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #7      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #8      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #9      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #10     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #11     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>
           
           
[ +262 ms] ensureAnalyticsSent: 260ms
[   +1 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 255

```

### :scroll: Pubspec.yaml

```
name: ringers_pos
description: Ringers POS Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.10+1

environment:
  sdk: ">=2.15.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  json_annotation: ^4.4.0
  intl: ^0.17.0
  dio: ^4.0.6
  get_it: ^7.2.0
  stacked: ^2.3.0
  stacked_services: ^0.8.17
  socket_io_client: ^1.0.2
  pretty_dio_logger: ^1.1.1
  graphql: ^5.0.1
  gql_dio_link: ^0.2.2
  crypto: ^3.0.1
  window_manager: ^0.2.1
  auto_size_text: ^3.0.0
  event_bus: ^2.0.0
  flutter_svg: ^1.0.3
  sentry_flutter: ^6.4.0
  flutter_dotenv: ^5.0.2
  yaml: ^3.1.0
  naeilsg_api_pkg:
    git:
      url: git@github.com:rng-mvp/naeilsg_api_pkg.git
      ref: main
  get: ^4.6.3
  flutter_acrylic: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.4
  json_serializable: ^6.1.5
  msix: ^3.5.1
  stacked_generator: ^0.6.2
  build_runner: ^2.1.8

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - pubspec.yaml
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: sdGothicMedium
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoM.ttf
    - family: sdGothicHeavy
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoH.ttf
    - family: sdGothicRegular
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoR.ttf
    - family: sdGothicBold
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoB.ttf
    - family: sdGothicLight
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoL.ttf
    - family: sdGothicExtraBold
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoEB.ttf
    - family: sdGothicSemiBold
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoSB.ttf
    - family: sdGothicThin
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoT.ttf
    - family: sdGothicUltraLight
      fonts:
        - asset: assets/fonts/AppleSDGothicNeo/AppleSDGothicNeoUL.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

msix_config:
  app_installer: 
    publish_folder_path: D:\Project\Publish
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false
  display_name: Ringers POS
  publisher_display_name: NaeilSG
  identity_name: NaeilSG.Ringers.POS
  logo_path: .\ringers.png
  capabilities: "internetClient,location,microphone,webcam"
```
