### ISSUE TITLE
[BUG] protocol_activation is not removed from registry on uninstall

### ISSUE THREAD

**Issue by canastro** [YehudaKremer/msix#133]
### :information_source: Info

**Version: `v3.6.0`**

### :speech_balloon: Description
I'm using `protocol_activation` and everything seems to be working as expected except that when I uninstall the application, the registry entry under `HKEY_CURRENT_USER/Software/Classes/my_protocol` does not get removed.

### :scroll: Pubspec.yaml
```yml
msix_config:
  display_name: Something
  publisher_display_name: Something GmbH
  identity_name: Something.Else
  capabilities: "internetClientServer"
  logo_path: "windows/runner/resources/app_icon.png"
  protocol_activation: my_protocol
```
