### ISSUE TITLE
[BUG] Cannot run AppInstaller generated

### ISSUE THREAD

**Issue by iqfareez** [YehudaKremer/msix#148]
### :information_source: Info

**Version: `3.6.3`**

### :speech_balloon: Description

I tried to package to AppInstaller, so I run the following command.

```ps
flutter pub run msix:publish
```
Output:
```ps
running "flutter build windows"...     38.3s
building msix files...                 18.5s
packing msix files...                  12.6s
publishing...                          0.2s
appinstaller created: .\build\windows/flutter_application_1.appinstaller
```

The file successfully generated, but when opening the installer:

![image](https://user-images.githubusercontent.com/60868965/184028453-a505554c-fe50-491f-b0cc-56cab18b5073.png)

An error `Cannot open app package` occur with the reason `Error in parsing the app package`.

_Note: I run the `.msix` installer without problem._

### :scroll: Pubspec.yaml

```yaml
name: flutter_application_1
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  msix: ^3.6.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

msix_config:
  display_name: My meow app
  publisher_display_name: Muhammad Fareez Iqmal
  identity_name: fareez.meow.app
  msix_version: 0.1.0.7
  logo_path: ".\\assets\\logo\\app-logo.png"
  app_installer:
    publish_folder_path: ".\\build\\windows"
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false
  capabilities: "internetClient"
  certificate_path: "C:\\Users\\Iqmal\\CERTIFICATE.pfx"
  certificate_password: 1234
```
