### ISSUE TITLE
[BUG] Certificate password is empty, check "msix_config: certificate_password" at pubspec.yaml

### ISSUE THREAD

**Issue by MTRNord** [YehudaKremer/msix#16]
### :information_source: Info

Version: `0.1.6`

### :speech_balloon: Description

The bin says `Certificate password is empty, check "msix_config: certificate_password" at pubspec.yaml` even when `certificate_password` was set to "placeholder".

### :scroll: Pubspec.yaml

Important part of the pubspec msix section (at runtime password and cert file get overwritten using python):

```
msix_config:
  display_name: Famedly
  publisher_display_name: Famedly
  identity_name: com.famedly.chat
  msix_version: 0.28.1.0 
  publisher: CN=Famedly GmbH
  certificate_path: ./code-signing-famedly.pfx
  certificate_password: placeholder
  capabilities: 'internetClient,location,microphone,webcam,chat,picturesLibrary,videosLibrary,documentsLibrary'
```
