### ISSUE TITLE
Please help me for toast notification [Help] 

### ISSUE THREAD

**Issue by MohsenHaydari** [YehudaKremer/msix#162]
I wrote a package for notification that you can see [here](https://pub.dev/packages/windows_notification)
everything is ok but the action event not working ( other than the system type)

When I use another ```AMUID``` in the plugin that I get from Windows with the Get-StartApps command in Powershell, the action works fine.

with package mode with ```msix```, I don't use any ```AMUID``` to display the notification, the icon and the name of the application are displayed correctly, but I don't receive the action event.

Manifest

```
<Application Id="mrt" Executable="mrt_application.exe" EntryPoint="Windows.FullTrustApplication">

 </uap:Extension>
          <com:Extension Category="windows.comServer">
          <com:ComServer>
            <com:ExeServer Executable="mrt_application.exe" Arguments="-ToastActivated" DisplayName="Toast activator">
              <com:Class Id="c1ca7cbb-0a44-44b5-8ded-8cd054d5365a" DisplayName="Toast activator"/>
            </com:ExeServer>
          </com:ComServer>
        </com:Extension>
        <desktop:Extension Category="windows.toastNotificationActivation">
          <desktop:ToastNotificationActivation ToastActivatorCLSID="c1ca7cbb-0a44-44b5-8ded-8cd054d5365a"/>
        </desktop:Extension>
```
YAML

```
msix_config:
  display_name: MRT NETWORK
  publisher_display_name: MRT
  identity_name: MRTNETWORK.MRT
  msix_version: 1.0.0.0
  logo_path: ..\logo2.png
  capabilities: internetClient, location
  certificate_path: ...\mrt_win.pfx
  certificate_password: ****
  toast_activator: #<-- toast notifications configuration
    clsid: c1ca7cbb-0a44-44b5-8ded-8cd054d5365a
    arguments: "-ToastActivated"
    display_name: "Toast activator"
  app_installer:
    publish_folder_path: C:\in_work\mrt_app\windows_installer

```
please help me, thanks
