### ISSUE TITLE
[BUG] Signing fails with error

### ISSUE THREAD

**Issue by MTRNord** [YehudaKremer/msix#17]
### :information_source: Info

Version: `0.1.8`

### :speech_balloon: Description

The signing fails with:

```
getting config values..  [√]
validate config values..  [√]
create icons folder..  [√]
copy icons..  [√]
create manifest file..  [√]
copy VCLibs files..  [√]
packing..  [√]
singing..  Error information: "Error: Store::ImportCertObject() failed." (-2146893808/0x80090010)

SignTool Error: An unexpected internal error has occurred.
```

### :scroll: Pubspec.yaml

```
msix_config:
  display_name: Famedly
  publisher_display_name: Famedly
  identity_name: com.famedly.chat
  msix_version: 0.28.1.0  
  publisher: CN=Famedly GmbH
  certificate_path: ./code-signing-famedly.pfx
  certificate_password: placeholder
  capabilities: 'internetClient,location,microphone,webcam,chat,picturesLibrary,videosLibrary,documentsLibrary'
```
