### ISSUE TITLE
[BUG] Image reference "Images\BadgeLogo.png": The image "Images\BadgeLogo.scale-100.png" is not valid

### ISSUE THREAD

**Issue by calcitem** [YehudaKremer/msix#170]
### :information_source: Info

**Version: `v3.7.0`**

### :speech_balloon: Description

Thanks for creating this package.

Feedback a problem, when I use the [source code](https://github.com/calcitem/Sanmill/tree/master/src/ui/flutter_app) to generate [msix file](https://github.com/calcitem/Sanmill/releases/download/v3.3.0/sanmill.msix) through `flutter pub run msix:create` command and use Windows App Cert Kit to check and report an error:

```
App manifest resources tests

FAILED
App resources
Error Found: The app resources validation test detected the following errors:
Image reference "Images\BadgeLogo.png": The image "Images\BadgeLogo.scale-100.png" has an ABGR value "0xFE57B3F0" at position (0, 0) that is not valid. The pixel must be white (##FFFFFF) or transparent (00######).
Impact if not fixed: The app might not install if the strings or images declared in your app’s manifest are incorrect. If the app does install with these errors, your app’s logo or other images used by your app might not display correctly.
How to fix: Fix the problem indicated by the error message. See the link below for more information:
```

I didn't find a solution to this problem.

According to [Windows App Certification Badge Logo rules](https://social.msdn.microsoft.com/Forums/Windows/en-US/04dfcf78-ebb4-4568-b35b-b56acc2fee06/windows-app-certification-badge-logo-rules?forum=wpsubmit):

> So far as I'm concerned, the badge logo can only contain white or transparent color to work properly unlike the other image assets. Because the badge will be visible on the lock screen for notification not on your tile.

So I need to modify the badge logo so that all pixels are transparent or white, but I can't find where to modify it.

I then forcibly submitted this msix file to Microsoft for review, but unfortunately, it failed. The information provided by Microsoft is:

```
10.3 App Is Testable
The product failed to install through the Store. 
Tested devices: Dell Inspiron 13-5379, Microsoft Surface Laptop
```

The icon looks like this:

![BadgeLogo scale-100](https://user-images.githubusercontent.com/51521682/211357621-c72cf1bf-b5f3-4cc3-b89f-b4300916276d.png)

### :scroll: Pubspec.yaml

**We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect**

```yaml
name: sanmill
description: Sanmill is a open-source, powerful UCI-like Nine Men's Morris (and its variants) program.
publish_to: none
version: 3.3.0+3333

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  animated_text_kit: 4.1.1
  catcher:
    git:
      url: https://gitlab.com/calcitem/catcher.git
  collection: ^1.16.0
  copy_with_extension: ^4.0.4
  cupertino_icons: ^1.0.5
  device_info_plus: ^7.0.1
  extended_sliver: ^2.1.3
  feedback: ^2.5.0
  filesystem_picker: ^3.1.0
  fluentui_system_icons: ^1.1.189
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_email_sender: ^5.2.0
  flutter_localizations:
    sdk: flutter
  flutter_platform_alert: ^0.3.0
  flutter_picker: ^2.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^3.0.2
  intl: ^0.17.0
  json_annotation: ^4.7.0
  logger: ^1.1.0
  marquee: ^2.2.3
  package_info_plus: ^3.0.2
  path_provider: ^2.0.11
  share_plus: ^6.3.0
  sliver_tools: ^0.2.8
  soundpool: ^2.3.0
  soundpool_windux:
    git:
      url: https://gitlab.com/calcitem/soundpool.git
      ref: windows_linux_support
      path: soundpool_windux
  url_launcher: ^6.1.7
  uuid: ^3.0.7

dev_dependencies:
  build_runner: ^2.3.0
  copy_with_extension_gen: ^4.0.4
  flutter_driver:
    sdk: flutter
  flutter_gen_runner: ^5.0.3
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.1
  mockito: any
  msix: ^3.7.0
  source_gen: ^1.2.6
  test: any

flutter_gen:
  output: lib/generated/assets/

flutter:
  generate: false
  uses-material-design: true
  assets:
    - assets/files/git-branch.txt
    - assets/files/git-revision.txt
    - assets/licenses/GPL-3.0.txt
    - assets/audios/draw.mp3
    - assets/audios/fly.mp3
    - assets/audios/go.mp3
    - assets/audios/illegal.mp3
    - assets/audios/lose.mp3
    - assets/audios/mill.mp3
    - assets/audios/place.mp3
    - assets/audios/remove.mp3
    - assets/audios/select.mp3
    - assets/audios/win.mp3

flutter_intl:
  enabled: true

msix_config:
  display_name: Mill (N Men's Morris)
  publisher_display_name: Calcitem Studio
  identity_name: 25314CalcitemStudio.Sanmill
  publisher: CN=3413C020-B420-4E0A-8687-A2C35E878F3A
  logo_path: ..\..\..\fastlane\metadata\android\en-US\images\icon.png
  capabilities: "documentsLibrary"
  languages: en-us, zh-cn
  execution_alias: mill
  store: true
```

**Comment by YehudaKremer** [comment]
Hello

I don't think the logo is problematic, most likely the publishing process failed for another reason.

when you create a msix file without `store: true` (testing), is the app installation working on your pc?

maybe the Microsoft store tried to install your app on a faulted machine, you should try again.

**Comment by calcitem** [comment]
Hi! If I delete `store: true`, regardless of whether `test_certificate.pfx` is installed or not, after clicking the msix file, it prompts "The publisher certificate for this application package cannot be verified."

```
PS D:\Repo\Sanmill\src\ui\flutter_app> flutter pub run msix:create
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
running "flutter build windows"...     6.3s
building msix files...                 1.1s
packing msix files...                   

Do you want to install the certificate: "test_certificate.pfx" ? (y/N) y
the certificate installed successfully 
msix created: build/windows/runner/Release/sanmill.msix


PS D:\Repo\Sanmill\src\ui\flutter_app> flutter pub run msix:create
Flutter assets will be downloaded from https://storage.flutter-io.cn. Make sure you trust this source!
running "flutter build windows"...     5.9s
building msix files...                 1.2s
packing msix files...                   

Do you want to install the certificate: "test_certificate.pfx" ? (y/N) n
msix created: build/windows/runner/Release/sanmill.msix
```

If I keep `store: true`, generate the msix file, decompress it, use the `Add-AppxPackage –Register AppxManifest.xml` command in PowerShell to install it, and the execution is OK.

**Comment by YehudaKremer** [comment]
Jod job👍

**Comment by xenSlayer** [comment]
@calcitem I am getting the same error response from microsoft during app submission. What fixed your problem? I submitted twice but got the same response. 

my msix config:

```
msix_config:
  display_name: xen
  publisher_display_name: xen lab
  identity_name: 1133xenlab.xenapplication
  languages: en-us, ja-jp
  publisher: CN=93573BG3-EFDF-4BC2-A92B-BEWW613F70X3
  logo_path: C:\Users\xxx\Desktop\xen\resources\icons\logo.png
  store: true
  enable_at_startup: true
  capabilities: internetClient
  sign_msix: false
  install_certificate: false
```
