### ISSUE TITLE
Outdated image dependency

### ISSUE THREAD

**Issue by davidpanic** [YehudaKremer/msix#171]
### :information_source: Info

**Version: `3.7.0`**

### :speech_balloon: Description

```
Because msix 3.7.0 depends on image ^3.1.0 and no versions of msix match >3.7.0 <4.0.0, msix ^3.7.0 requires image ^3.1.0.
So, because [app] depends on both image ^4.0.8 and msix ^3.7.0, version solving failed.
pub get failed (1; So, because [app] depends on both image ^4.0.8 and msix ^3.7.0, version solving failed.)
```

### :scroll: Pubspec.yaml

```yaml
dependencies:
  image: ^4.0.8
dev_dependencies:
  msix: ^3.7.0
```
