### ISSUE TITLE
[BUG] App logo smaller than other ones

### ISSUE THREAD

**Issue by mgenware** [YehudaKremer/msix#179]
I've already had the `logo_path` point to a 1024x1024 png file.

Most app logos in windows 11 store are like this:
![image](https://user-images.githubusercontent.com/11565096/219608928-d50338a3-e11a-44df-b1e6-a8b9b3b9dcfc.png)

Apps built with this plugin are like:
![image](https://user-images.githubusercontent.com/11565096/219609133-e1824ac3-3671-47f8-8753-0a588e1d8f47.png)

My config:
```yaml
msix_config:
  display_name: -
  publisher_display_name: -
  publisher: -
  identity_name: -
  msix_version: 2.0.0.0
  logo_path: .\icon.png
  languages: en
  assets_directory_path: res
```
