### ISSUE TITLE
[FEATURE REQUEST] Support for config path in the msix creation command

### ISSUE THREAD

**Issue by milindgoel15** [YehudaKremer/msix#220]
### :speech_balloon: Description
As per the docs, the config node has to be present in the pubspec file. Can you add support for custom config files and declaring paths in the command to use such config files? For example,

root > config > msix_config.yaml

the command would be: 
`dart run msix:create --config config/msix_config.yaml`

of course the config path will be optional, keeping default check to be in pubspec.

### :question: Platform
Is this feature request for a specific platform? E.g. Web / iOS / Android / Mac OS / Windows / Linux
N/A

**Comment by milindgoel15** [comment]
I was able to implement this. will create a PR soon.

**Comment by praxamarnix** [comment]
This would be great, since I have a couple of variables that are build dependent. For example, I want to send a different type of `--dart-fine="SOMESTUFF=$1"`. Meaning that I will have to generate that in some script before sending it over.

Or would it already be possible to add this in the dart command as an optional parameter?

**Comment by milindgoel15** [comment]
> For example, I want to send a different type of `--dart-fine="SOMESTUFF=$1"`. 

Can you provide an example for this? Some kind of flavor?

**Comment by praxamarnix** [comment]
For example I want to be able to send a dart-define into the windows_build_args. That would not be possible with only pubspec.yaml. Or otherwise I will have to generate pubspec.yaml just before compilation as a workaround.

In this example I'm trying to set a database that could be either development or production. But one could also think of secrets that need to be compiled into the code.

```yaml
msix_config:
  windows_build_args: --dart-define="DATABASE=production"
```

**Comment by milindgoel15** [comment]
Understood what you meant. Might be possible but have to test it. Would you be able to provide an example repository?

**Comment by milindgoel15** [comment]
> But I want the `--dart-define` to be more flexible and not hard-coded in my pubspec.yaml as described here in this ticket as well.

As an update to this specific feature request, I have added the way to define variables for --dart-define but in the form of a command option since we cannot modify the yaml files on demand. So the choice will work in the way of flavours.

example:

```yaml
msix_config-production:
   display_name: msixflavor
   publisher_display_name: test
   identity_name: com.example.msixflavor
   msix_version: 1.0.0.0
   windows_build_args: --dart-define="DATABASE=production"

msix_config-development:
   display_name: msixflavor
   publisher_display_name: test
   identity_name: com.example.msixflavor.dev
   msix_version: 1.0.0.0
   windows_build_args: --dart-define="DATABASE=development"
```

So with the sample example, the commands will be like these respectively.

```console
dart run msix:create --flavour="production"
```
```console
dart run msix:create --flavour="development"
```

Will add the new changes to my current PR
