### ISSUE TITLE
[BUG] Wrong publisher name on installing msix in windows using app installer

### ISSUE THREAD

**Issue by milindgoel15** [YehudaKremer/msix#221]
### :information_source: Info

**Version: `3.16.1`**

### :speech_balloon: Description

```yaml
msix_config:
   display_name: WeatherWise
   publisher_display_name: MGProjects  ---> this appears as Msix testing when installing 
   identity_name: com.mgprojects.weatherwise
   msix_version: 1.0.0.1
   logo_path: D:\Programming\Flutter-projects\WeatherWiseApp\weatherwise\assets\images\windows\logo_light.png
   capabilities: internetClient, location

```

The publisher name doesn't come as per the one written in the config.
<img src="https://github.com/YehudaKremer/msix/assets/45682747/fdf725f1-ae91-4fcb-9c2f-17c4a755f46d" width="400" />

msix logs:
[pub_log.txt](https://github.com/YehudaKremer/msix/files/12326935/pub_log.txt)

### :scroll: Pubspec.yaml

**We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect**

the copy of pubspec is also there in pub_log.txt.
