### ISSUE TITLE
[BUG] Do you want to install the certificate: "SIDEKICK-CERT.pfx" ? (y/N) 

### ISSUE THREAD

**Issue by aguilaair** [YehudaKremer/msix#230]
### :information_source: Info

**Version: `3.16.0`**

### :speech_balloon: Description

**Enter a description of your problem here.<br />
Any logs, error and assets you have that can help to find this bug.<br />
To run the tool with extended logs use the `-v` argument, for example: `flutter pub run msix:create -v`**

See: https://github.com/fluttertools/sidekick/issues/307 with Action https://github.com/fluttertools/sidekick/actions/runs/6072041308

The output for a non-store version is:

```
Run flutter pub run msix:create
building msix files...                  OK 15.9s
packing msix files...                  IN PROGRESS

Unhandled exception:
type 'Null' is not a subtype of type 'FutureOr<String>'
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:42:41)
#1      Prompter.prompt.<anonymous closure>.<anonymous closure> (package:console/src/prompt.dart:222:19)
#2      new Future.<anonymous closure> (dart:async/future.dart:256:37)
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
Do you want to install the certificate: "SIDEKICK-CERT.pfx" ? (y/N) 
Error: Process completed with exit code 1.
```

### :scroll: Pubspec.yaml

**We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect**

```yaml
msix_config:
    display_name: Sidekick DEV Build
    publisher_display_name: Eduardo M.
    identity_name: 44484EduardoM.SidekickFlutter
    publisher: CN=1E781C91-227E-4505-B5B8-7E5EFE39D3A6
    msix_version: 1.0.0.0
    logo_path: assets\promo-windows\icon.png
    architecture: x64
    capabilities: "internetClient,removableStorage"
    certificate_path: windows\SIDEKICK-CERT.pfx
    certificate_password: ***
    install-certificate: false
    build_windows: false
    store: false
```

Full pubspec in: https://github.com/fluttertools/sidekick/blob/main/pubspec.yaml MISX info is appended on the CI here: https://github.com/fluttertools/sidekick/blob/57215e1910413341b6974fbfc38b6a3f94342b1f/.github/workflows/main.yaml#L143
