### ISSUE TITLE
[BUG] Failed to parse publisher because `ST` is not a valid key

### ISSUE THREAD

**Issue by praxa-enzo** [YehudaKremer/msix#232]
### :information_source: Info

**Version: `3.16.1`**

### :speech_balloon: Description

When running the following command in our GitHub actions pipeline: 
```
flutter pub run msix:create -v --build-windows false --output-path ./msix --sign-msix false
```

We get the following error:
```
C=country, ST=province, O=companyName, OU=Development, CN=companyName' violates pattern constraint of '(CN|L|O|OU|E|C|S|STREET|T|G|I|SN|DC|SERIALNUMBER|Description|PostalCode|POBox|Phone|X21Address|dnQualifier|(OID\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))+))=(([^,+="<>#;])+|".*")(, ((CN|L|O|OU|E|C|S|STREET|T|G|I|SN|DC|SERIALNUMBER|Description|PostalCode|POBox|Phone|X21Address|dnQualifier|(OID\.(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))+))=(([^,+="<>#;])+|".*")))*
```

The `ST` key is not part of the regular expression, while it is a valid key in the subject of our certificate.
A valid key would be `S`. But if we use this key then it is not possible to sign the installer afterwards because the app manifest publisher name does not match the subject of the certificate.
Would it be possible to make the publisher as described in the pubspec below a valid publisher?

### :scroll: Pubspec.yaml

```yaml
name: productName
description: description

publish_to: 'none'

version: 0.6.0

environment:
  sdk: 3.0.3
  flutter: 3.10.4

dependencies:
  bloc: 8.0.3
  collection: 1.17.1
  complete_timer: 1.0.0
  data_table_2: 2.4.2
  event: 2.1.2
  file_picker: 5.2.11
  file_saver: 0.1.0
  fl_chart: 0.51.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  flutter_mobx: 2.0.6+5
  get_it: 7.2.0
  google_fonts: 4.0.3
  http: 0.13.5
  iirjdart: 0.1.0
  intl: 0.17.0
  meta: 1.9.1
  mobx: 2.1.4
  path: 1.8.3
  queue: 3.1.0+2
  uuid: 3.0.7
  version: 3.0.2
  window_manager: 0.3.5
  cupertino_icons: 1.0.4

dev_dependencies:
  build_runner: 2.3.3
  dependency_validator: 3.2.2
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  mobx_codegen: 2.2.0
  mockito: 5.4.0
  msix: 3.16.1

flutter:
  uses-material-design: true

  assets:
    - lib/ui/assets/afi_indicators/
    - lib/ui/assets/icons/
    - lib/ui/assets/logo/
    - lib/ui/assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: lib/ui/assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
          style: normal
        - asset: lib/ui/assets/fonts/Roboto/Roboto-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/ui/assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
          style: normal
        - asset: lib/ui/assets/fonts/Roboto/Roboto-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/ui/assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
          style: normal
        - asset: lib/ui/assets/fonts/Roboto/Roboto-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/ui/assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
          style: normal
        - asset: lib/ui/assets/fonts/Roboto/Roboto-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/ui/assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
          style: normal
        - asset: lib/ui/assets/fonts/Roboto/Roboto-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/ui/assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
          style: normal
        - asset: lib/ui/assets/fonts/Roboto/Roboto-BlackItalic.ttf
          weight: 900
          style: italic

msix_config:
  publisher: C = country, ST = province, O = companyName, OU = Development, CN = companyName
  display_name: applicationName
  publisher_display_name: companyName
  identity_name: identity
  logo_path: lib/ui/assets/logo/logo.png
```
