### ISSUE TITLE
[BUG] This doesn't run within a Github Action. Any ideas, please?

### ISSUE THREAD

**Issue by hobleyd** [YehudaKremer/msix#236]
### :information_source: Info

**Version: `(msix: ^3.16.2)`**

### :speech_balloon: Description

It fails when run as a Github Action - possibly due to interactive question being asked, but I did specify install_certificate:true so unclear why it would ask for this.
```
Run dart run msix:create --certificate-path sharpblue.pfx
building msix files...                  /-|\|-\|/\|\|/-/\\/\/-\|\|/|-/|-/\-|\/\-|-\/-|-/\-\|-/-\/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-18.0s
packing msix files...                   /-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\|/-\ 

Unhandled exception:
type 'Null' is not a subtype of type 'FutureOr<String>'
#0      _AsyncCompleter.complete (dart:async/future_impl.dart:42:41)
#1      Prompter.prompt.<anonymous closure>.<anonymous closure> (package:console/src/prompt.dart:222:19)
#2      new Future.<anonymous closure> (dart:async/future.dart:256:37)
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)
Do you want to install the certificate: "sharpblue.pfx" ? (y/n)
```

### :scroll: Pubspec.yaml

```
msix_config:
  build_windows: false
  capabilities: broadFileSystemAccess
  certificate_password: sharpblue
  display_name: Shackleton
  identity_name: au.com.sharpblue.shackleton
  install_certificate: true
  logo_path: assets\explorer.png
  publisher_display_name: SharpBlue
```

Any help gratefully accepted.
