### ISSUE TITLE
[BUG] Scaled down icons have darker borders

### ISSUE THREAD

**Issue by Tienisto** [YehudaKremer/msix#239]
### :information_source: Info

3.16.4

### :speech_balloon: Description

The generated icons have a dark border instead of fading to transparent.

On small images (like 44x44) this is very noticable.

Original:

![windows-icon-512](https://github.com/YehudaKremer/msix/assets/38380847/08ac21b0-ecdb-4211-8301-653004584c97)

Start Menu:

![grafik](https://github.com/YehudaKremer/msix/assets/38380847/114b419a-1568-48b4-b4c7-85ce7396223e)

I opened the generated icon in Gimp and put a white background to see if it is dark or transparent, apparently, this is dark.

![grafik](https://github.com/YehudaKremer/msix/assets/38380847/303c6bff-87d6-48f0-b503-87155922d1ea)

### :scroll: Pubspec.yaml

```yaml
msix_config:
  display_name: LocalSend
  publisher_display_name: Tien Do Nam
  identity_name: 11157TienDoNam.LocalSend
  logo_path: assets\packaging\windows-icon-512.png
  languages: en, ar, bn, cs, de, es-ES, fa, fr-FR, hu, in, it, iw, ja, ko, ne, nl, pl, pt-BR, ru, sv, tr, uk, zh-CN, zh-HK, zh-TW
  os_min_version: 10.0.19041.0

  startup_task:
    task_id: localsend
    enabled: false
    parameters: autostart
```
