### ISSUE TITLE
[FEATURE REQUEST] Add version number to the output name.

### ISSUE THREAD

**Issue by AurelienBallier** [YehudaKremer/msix#242]
Could you had an option to add 'msix_version' to 'output_name' without changing manually both parameters ?
Something like this in pubspec.yaml could be nice :
```
msix_config:
  display_name: My App
  publisher_display_name: Company
  identity_name: com.company.app
  msix_version: 1.0.0.0
  output_name: %display_name - %msix_version
```
