### ISSUE TITLE
 certificate could not be verified during msix installation

### ISSUE THREAD

**Issue by xenSlayer** [YehudaKremer/msix#245]
```
This app package’s publisher certificate could not be verified. 
Contact your system administrator or the app developer to obtain a new app package with verified certificates. 
The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)
```

msix_config:
```
msix_config:
  display_name: appname
  publisher_display_name: sweet apps
  identity_name: xxxxxxxx (given valid identity name obtained from ms dev account)
  publisher: xxxxxxxxxx (given valid publisher obtained from ms dev account)
  store: true
  enable_at_startup: true
  capabilities: internetClient, musicLibrary
  certificate_path: C:\Users\xxx\Desktop\xxx\resources\win_certificates\certificate.pfx
  certificate_password: xxxxxxxxxxxxxxxx
```

certificate generated using openssl
