### ISSUE TITLE
[BUG] Fails to run in 

### ISSUE THREAD

**Issue by xenSlayer** [YehudaKremer/msix#247]
### :information_source: Info

**Version: `msix: ^3.16.6`**

### :speech_balloon: Description

**Fails to build msix with git action**
<br />

`flutter pub run msix:create -v` log:
```
D:\a\xenmusic\xenmusic\packages\xenmusic\build\windows\runner\Release
[     0.169s] running "flutter build windows"...
[     0.169s] build windows files with the command: "flutter build windows"
[ 3m 47.404s] 
windows/flutter/CMakeLists.txt does not use FLUTTER_TARGET_PLATFORM, updating.
Building Windows application...                                   223.2s

Unhandled exception:
Build process failed.

#0      ProcessResultExtensions.exitOnError (package:msix/src/method_extensions.dart:61:7)
#1      WindowsBuild.build (package:msix/src/windows_build.dart:33:[18](https://github.com/xenSlayer/xenmusic/actions/runs/6914554811/job/18812507494#step:7:19))
<asynchronous suspension>
#2      Msix._buildMsixFiles (package:msix/msix.dart:107:[31](https://github.com/xenSlayer/xenmusic/actions/runs/6914554811/job/18812507494#step:7:32))
<asynchronous suspension>
#3      Msix._createMsix (package:msix/msix.dart:102:5)
<asynchronous suspension>
#4      Msix.create (package:msix/msix.dart:59:5)
<asynchronous suspension>
#5      main (file:///C:/hostedtoolcache/windows/flutter/stable-3.16.0-x64/.pub-cache/hosted/pub.dev/msix-3.16.6/bin/create.dart:4:3)
<asynchronous suspension>


melos run build_windows
  └> cd packages/xenmusic && dart run msix:create -v
     └> FAILED
ScriptException: The script build_windows failed to execute.
```

### :scroll: Pubspec.yaml

```
msix_config:
  display_name: xenmusic | the ultimate music app
  publisher_display_name: xen lab
  identity_name: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  languages: en-us
  publisher: CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  logo_path: ../../resources/icons/logo.png
  store: true
  enable_at_startup: true
  sign_msix: false
  install_certificate: false
  output_path: ../../release
```
