### ISSUE TITLE
[BUG] Couldn't resolve the package 'flutter_gen'

### ISSUE THREAD

**Issue by wim07101993** [YehudaKremer/msix#267]
### :information_source: Info

msix version: `3.16.7`

`flutter doctor` output:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.22.0, on Microsoft Windows [Version 10.0.22631.3447], locale en-US)
[✓] Windows Version (Installed version of Windows is version 10 or higher)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Chrome - develop for the web
[✓] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.9.7)
[!] Android Studio (not installed)
[✓] Connected device (3 available)
[✓] Network resources
```

### :speech_balloon: Description

**Enter a description of your problem here.<br />**
`flutter run` does work
`flutter run msix:create` fails
`dart run msix:create` fails

**Any logs, error and assets you have that can help to find this bug.<br />**
github action with logs: https://github.com/wim07101993/qr_code_generator/actions/runs/9133440507/job/25116922893

**To run the tool with extended logs use the `-v` argument, for example: `lutter pub run msix:create -v`**

### :scroll: Pubspec.yaml

```
ame: qr_code_generator
description: Generates different kinds of QR-codes, like a link or a payment request.
publish_to: 'none'
version: 0.4.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ansicolor: ">=2.0.0 <3.0.0"
  auto_route: ">=8.0.0 <9.0.0"
  behaviour: ">=3.0.0 <4.0.0"
  collection: ">=1.0.0 <2.0.0"
  download: ">=1.0.0 <2.0.0"
  file_picker: ">=8.0.0 <9.0.0"
  flex_color_picker: ">=3.0.0 <4.0.0"
  flutter:
    sdk: flutter
  flutter_app_base:
    git:
      url: https://github.com/wim07101993/flutter_app_base.git
      ref: 921445b60c8acab050ae9f365078a4208c6c1f13
  flutter_fox_logging: ">=2.0.0 <3.0.0"
  flutter_localizations:
    sdk: flutter
  function_tree: ">=0.0.0 <1.0.0"
  get_it: ">=7.0.0 <8.0.0"
  intl: ">=0.0.0 <1.0.0"
  path: ">=1.0.0 <2.0.0"
  path_provider: ">=2.0.0 <3.0.0"
  qr: ">=3.0.0 <4.0.0"
  qr_flutter: ">=4.0.0 <5.0.0"
  share_plus: ">=9.0.0 <10.0.0"
  shared_preferences: ">=2.0.0 <3.0.0"


dev_dependencies:
  auto_route_generator:
  build_runner:
  flutter_test:
    sdk: flutter
  lint:
  msix: ">=3.0.0 <4.0.0"

flutter:
  uses-material-design: true
  generate: true

msix_config:
  display_name: QR-generator
  publisher_display_name: wim07101993
  publisher: CN=C359B0E3-0A9C-4C4C-9037-E1B393CA187E
  identity_name: 38383wim07101993.QR-generator
  msix_version: 0.4.0.0
  languages: nl-be, en-gb
  store: true
  logo_path: logo_without_background.png
```
