### ISSUE TITLE
[BUG] "Flag option "store" should not be given a value" error when using msix in command line

### ISSUE THREAD

**Issue by mregnauld** [YehudaKremer/msix#278]
### :information_source: Info

**Version: `3.16.7`**

### :speech_balloon: Description

When running the following .bat script on Windows:

```batch
dart run msix:create ^
  --display-name="MyAppr" ^
  --publisher-display-name="Matthieu R" ^
  --publisher="CN........" ^
  --identity-name="MatthieuR.MyApp" ^
  --version="3.2.1.0" ^
  --logo-path=".\assets\icons\logo_play_store.jpg" ^
  --capabilities="internetClient" ^
  --languages="en-us, fr-fr" ^
  --output-name="myapp" ^
  --store=true
```

I got the following error:

```
Unhandled exception:
FormatException: Flag option "store" should not be given a value.
#0      Parser._validate (package:args/src/parser.dart:311:21)
#1      Parser._handleLongOption (package:args/src/parser.dart:272:9)
#2      Parser._parseLongOption (package:args/src/parser.dart:264:12)
#3      Parser.parse (package:args/src/parser.dart:86:11)
#4      ArgParser.parse (package:args/src/arg_parser.dart:334:42)
#5      Configuration._parseCliArguments (package:msix/src/configuration.dart:421:20)
#6      Configuration.getConfigValues (package:msix/src/configuration.dart:78:5)
#7      Msix._initConfig (package:msix/msix.dart:97:19)
#8      Msix.create (package:msix/msix.dart:58:11)
#9      main (file:///C:/Users/Matt/AppData/Local/Pub/Cache/hosted/pub.dev/msix-3.16.7/bin/create.dart:4:25)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

which is quite annoying if you want to use it in a CI/CD, since I don't want to put sensitive information in my pubspec.yaml file.

Did I miss anything?

### :scroll: Pubspec.yaml

```yaml
name: myapp
description: "MyApp"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.12+14

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  simple_animations: ^5.0.2
  drift: ^2.15.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.1.2
  path: ^1.9.0
  cryptography: ^2.7.0
  encrypt: ^5.0.3
  pointycastle: ^3.7.4
  flutter_keyboard_visibility: ^6.0.0
  dotted_border: ^2.1.0
  firebase_core: ^3.1.1
  firebase_crashlytics: ^4.0.2
  internet_connection_checker: ^1.0.0+1
  material_design_icons_flutter: ^7.0.7296
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  store_redirect: ^2.0.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.1
  go_router: ^14.1.4
  shared_preferences: ^2.2.2
  flutter_riverpod: ^2.4.10
  json_annotation: ^4.8.1
  web_socket_channel: ^2.4.4
  widgetbook_annotation: ^3.1.0
  widgetbook: ^3.7.1
  web: ^0.5.1
  window_manager: ^0.3.9
  url_launcher: ^6.3.0
  diacritic: ^0.1.5
  equatable: ^2.0.5
  back_button_interceptor: ^7.0.2
  package_info_plus: ^8.0.0
  device_info_plus: ^10.1.0
  uuid: ^4.4.0

dev_dependencies:
  drift_dev: ^2.15.0
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.4.4
  flutter_lints: ^3.0.1
  golden_toolkit: ^0.15.0
  widgetbook_generator: ^3.7.0
  msix: ^3.16.7

# The following section is specific to Flutter packages.
flutter:

  # Internationalisation :
  generate: true

  # Material design icons :
  uses-material-design: true

  # images :
  assets:
    - assets/config/
    - assets/images/
    - assets/icons/

  # fonts :
  fonts:
    - family: Base
      fonts:
        - asset: assets/fonts/lexend_light.ttf
          weight: 300
        - asset: assets/fonts/lexend_regular.ttf
          weight: 400
    - family: Mot
      fonts:
        - asset: assets/fonts/inconsolata_semibold.ttf
          weight: 600
    - family: Mono
      fonts:
        - asset: assets/fonts/mono_regular.ttf

```

**We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect**
