### ISSUE TITLE
[BUG] This app package is not signed with a trusted certificate. 

### ISSUE THREAD

**Issue by SahajRana** [YehudaKremer/msix#28]
### :information_source: Info

Version: `v0.1.15`

### :speech_balloon: Description

Misx Installer gives this message 
```
This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)
```
and hence cant install the app on windows with msix.

```
msix_config:
  display_name: myCompany
  publisher_display_name: myCompany Pvt Ltd
  identity_name: com.myCompany
  msix_version: 1.0.0.0
  certificate_path: certificates\certificate.pfx
  certificate_password: pass...
  publisher: E=s..gmail.com, CN=myCompany, OU=myCompany, O=myCompany Pvt Ltd, L=Delhi, S=DL, C=IN
  logo_path: windows\runner\resources\app_logo.png
  start_menu_icon_path: windows\runner\resources\app_logo.png
  tile_icon_path: windows\runner\resources\app_logo.png
  vs_generated_images_folder_path: images
  icons_background_color: transparent
  architecture: x64
  capabilities: 'internetClient'
```
