### ISSUE TITLE
[BUG] Wrong executable "crashpad_handler.exe" in generated AppxManifest.xml

### ISSUE THREAD

**Issue by hig-dev** [YehudaKremer/msix#287]
### :information_source: Info

**Version: `msix: 3.16.8`**

### :speech_balloon: Description

I am using the command: 

When I inspect the created .msix, I can see that the _AppxManifest.xml_ contains the wrong executable:

### :scroll: AppxManifest.xml
```
(...)
<Applications>
  <Application Id="myapp" Executable="crashpad_handler.exe" EntryPoint="Windows.FullTrustApplication">
    (...)
    <Extensions>
     <uap3:Extension Category="windows.appExecutionAlias" Executable="crashpad_handler.exe" EntryPoint="Windows.FullTrustApplication">
       <uap3:AppExecutionAlias>
         <desktop:ExecutionAlias Alias="myappalias.exe" />
         </uap3:AppExecutionAlias>
     </uap3:Extension>
    </Extensions>
 </Application>
</Applications>
(...)
```

The build directory contains the following executables:
- crashpad_handler.exe
- myapp.exe

The msix package chooses the wrong executable and as a result the installed app crashes on the start.

### :scroll: Pubspec.yaml
```
name: myapp
description: My app.
version: 1.0.0
environment:
  sdk: '>=3.2.0 <4.0.0'

publish_to: none

dependencies:
  (...)

dev_dependencies:
  msix: ^3.16.8
  (...)

msix_config:
  display_name: My App
  publisher: CN=(...)
  publisher_display_name: HIG Studio
  identity_name: (...)
  logo_path: "../Graphics/AppIcon/icon.png"
  trim_logo: false
  capabilities: internetClient
  languages: en-us, de-de, nl-nl
  execution_alias: myappalias
  store: true
  build_windows: false
```
