### ISSUE TITLE
[BUG] Icon name not same in AppXManifest.xml

### ISSUE THREAD

**Issue by SahajRana** [YehudaKremer/msix#29]
### :information_source: Info

Version: `e.g. v0.1.15`

### :speech_balloon: Description

Icon name not same in AppXManifest.xml  as used in Pubspec.yaml

```
<?xml version="1.0" encoding="utf-8"?>
<Package xmlns="http://schemas.microsoft.com/appx/manifest/foundation/windows10" 
         xmlns:uap="http://schemas.microsoft.com/appx/manifest/uap/windows10" 
         xmlns:uap2="http://schemas.microsoft.com/appx/manifest/uap/windows10/2" 
         xmlns:uap3="http://schemas.microsoft.com/appx/manifest/uap/windows10/3" 
         xmlns:uap4="http://schemas.microsoft.com/appx/manifest/uap/windows10/4" 
         xmlns:uap6="http://schemas.microsoft.com/appx/manifest/uap/windows10/6" 
         xmlns:uap7="http://schemas.microsoft.com/appx/manifest/uap/windows10/7" 
         xmlns:uap8="http://schemas.microsoft.com/appx/manifest/uap/windows10/8" 
         xmlns:uap10="http://schemas.microsoft.com/appx/manifest/uap/windows10/10" 
         xmlns:iot="http://schemas.microsoft.com/appx/manifest/iot/windows10" 
         xmlns:desktop="http://schemas.microsoft.com/appx/manifest/desktop/windows10" 
         xmlns:desktop2="http://schemas.microsoft.com/appx/manifest/desktop/windows10/2" 
         xmlns:desktop6="http://schemas.microsoft.com/appx/manifest/desktop/windows10/6" 
         xmlns:rescap="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities" 
         xmlns:rescap3="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities/3" 
         xmlns:rescap6="http://schemas.microsoft.com/appx/manifest/foundation/windows10/restrictedcapabilities/6" 
         xmlns:com="http://schemas.microsoft.com/appx/manifest/com/windows10" 
         xmlns:com2="http://schemas.microsoft.com/appx/manifest/com/windows10/2" 
         xmlns:com3="http://schemas.microsoft.com/appx/manifest/com/windows10/3">
  <Identity Name="..." Version="1.0.0.0"
            Publisher="..." ProcessorArchitecture="x64" />
  <Properties>
    <DisplayName>...</DisplayName>
    <PublisherDisplayName>...</PublisherDisplayName>
    <Logo>Images\StoreLogo.png</Logo>
    <Description>...</Description>
  </Properties>
  <Resources>
    <Resource Language="en-us" />
  </Resources>
  <Dependencies>
    <TargetDeviceFamily Name="Windows.Desktop" MinVersion="10.0.17763.0" MaxVersionTested="10.0.19042.630" />
  </Dependencies>
  <Capabilities>
    <rescap:Capability Name="runFullTrust" />
    <Capability Name="internetClient" />
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
  </Capabilities>
  <Applications>
    <Application Id="..." Executable="....exe" EntryPoint="Windows.FullTrustApplication">
      <uap:VisualElements BackgroundColor="transparent"
        DisplayName="..." Square150x150Logo="Images\Square150x150Logo.png"
        Square44x44Logo="Images\Square44x44Logo.png" Description="..." >
        <uap:DefaultTile ShortName="Blup" Square310x310Logo="Images\LargeTile.png"
        Square71x71Logo="Images\SmallTile.png" Wide310x150Logo="Images\Wide310x150Logo.png">
          <uap:ShowNameOnTiles>
            <uap:ShowOn Tile="square150x150Logo"/>
            <uap:ShowOn Tile="square310x310Logo"/>
            <uap:ShowOn Tile="wide310x150Logo"/>
          </uap:ShowNameOnTiles>
        </uap:DefaultTile>
        <uap:SplashScreen Image="Images\SplashScreen.png"/>
        <uap:LockScreen BadgeLogo="Images\BadgeLogo.png" Notification="badge"/>
      </uap:VisualElements>
    </Application>
  </Applications>
</Package>  
```

### :scroll: Pubspec.yaml

We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect

```
msix_config:
  display_name: ...
  publisher_display_name: ...
  identity_name: ...
  msix_version: 1.0.0.0
  certificate_path: certificates\certificate.pfx
  certificate_password: ...
  publisher: ...
  logo_path: windows\runner\resources\app_logo.png
  start_menu_icon_path: windows\runner\resources\app_logo.png
  tile_icon_path: windows\runner\resources\app_logo.png
  vs_generated_images_folder_path: images
  icons_background_color: transparent
  architecture: x64
  capabilities: 'internetClient'
```

There are 2 things in it.

1.  Manifest shows that icons naming is different from what is passed in pubspec.yaml like,
`<Logo>Images\StoreLogo.png</Logo>` 
```
        DisplayName="..." Square150x150Logo="Images\Square150x150Logo.png"
        Square44x44Logo="Images\Square44x44Logo.png" Description="..." >
```

2. There is a wried spacing in between Capability XML block.
