### ISSUE TITLE
[BUG] get Microsoft Partner MSIX upload error: Apps are not allowed to have a Version with a revision number other than zero specified in the app manifest. The package yourapp.msix specifies 1.1.1.1.

### ISSUE THREAD

**Issue by DktPhl2019** [YehudaKremer/msix#296]
Using Windows 11 and Android Studio Ladybug | 2024.2.1 Patch 3, in the terminal, I type: 

flutter clean
then, click pub get
then, type: dart run msix:create

This generates msix file under the build folder in my project. 

There is no app manifest generated.

When I upload the msix into Microsoft Store, then I get the error: Apps are not allowed to have a Version with a revision number other than zero specified in the app manifest. The package MyApp.msix specifies 1.1.1.1.

I cannot find the app manifest file anywhere in my app folder. 

Could you please tell me what I am doing wrong. 

PUBSPEC.YAML

version: 1.1.1+0

msix_config:
  display_name: MyApp
  publisher_display_name: DMITRI KOZLOV
  identity_name: DMITRIKOZLOV.MyApp
  publisher: CN=generated number from Microsoft Store app Details
  msix_version: 1.1.1.1
  store: true

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^5.0.0
  path: ^1.9.0
  intl: ^0.19.0
  path_provider: ^2.1.5
  collection: ^1.18.0
  adaptive_theme: ^3.7.0
  msix: ^3.16.8

**Comment by DktPhl2019** [comment]
The App Manifest file should have all the app info.

First, I don't know how to create App Manifest file and how to populate the App Manifest file with all the required information.

I've read that it is generated automatically using the build under build windows folder, but I don't see it.

Once I have MSIX and the App Manifest, I don't know how to bundle it together.

I think I need to create .msixbundle file.

The problem is that I need to use Visual Studio to generate this bundle file.

I cannot open MSIX file in Visual Studio.

If I try to create the app package manually, then Microsoft Help says: "Note that MakeAppx.exe does not create an app package upload file (.appxupload or .msixupload), which is the recommended type of valid app package for submissions to Partner Center. The app package upload file is typically created as part of the Visual Studio packaging process, although it can also be created manually."

**Comment by Correct-Syntax** [comment]
You cannot have a revision number other than zero. See https://docs.flutter.dev/deployment/windows#updating-the-apps-version-number

**Comment by Chaphasilor** [comment]
@DktPhl2019 you need to change the msix version in your `pubspec.yaml` file:

```yaml
msix_config:
display_name: MyApp
publisher_display_name: DMITRI KOZLOV
identity_name: DMITRIKOZLOV.MyApp
publisher: CN=generated number from Microsoft Store app Details
msix_version: 1.1.1.1 # <--- THIS RIGHT HERE! Change it to 1.1.1.0, or 1.1.2.0, but keep the 0 at the end. Ideally it should always be the same version as your Android/iOS app version (without the stuff behind the +), with a 0 as the 4th digit
store: true
```
