### ISSUE TITLE
[BUG] Package sanity test - Archive file data\flutter_assets\NOTICES.Z found in package

### ISSUE THREAD

**Issue by mkulesh** [YehudaKremer/msix#299]
### :information_source: Info

**Version: `msix: 3.16.7`**

### :speech_balloon: Description

I build the msix in the local (non-store) mode in order to install it locally. The build, installation, and app itself work as desired. Submitting to MS Store also works without any problems. 

However, before submitting to MS Store, I test the app using Windows App Certification Kit, version 10.0.19041.685:
```
Windows App Certification Kit - Test Results
App name:
    Enhanced Music Controller
App publisher:
    Mikhail Kulesh
App version:
    2.14.3.0
App Architecture:
    x64
Kit Version:
    10.0.19041.685
OS Version:
    Microsoft Windows 11 Pro (10.0.22631.0)
OS Architecture:
    x64
Report time:
    13.03.2025 20:29:45
```

The result is failed for an optional test:
```
Package sanity test

FAILED
    Archive files usage

    Error Found: The archive files usage test has detected the following errors:
        Archive file data\flutter_assets\NOTICES.Z found in package.
    Impact if not fixed: Executable files inside archived files or self-extracting content are not signed during onboarding to the Microsoft Store, so they will not be able to run on Windows 10 S systems.
    How to fix: Evaluate any of the files flagged to determine if there is an impact to your app running in the Windows 10 S environment. If your app would be impacted, remove executable files from archived files and do not use self-extracting archives to place executable files on disk to avoid loss of app functionality. 
```

Why this file (data\flutter_assets\NOTICES.Z) is considered as executable by App Certification Kit? Is this file necessary in the distribution and when not how to delete it before msix is built?

### :scroll: Pubspec.yaml
```
# Project script for desktop versions (Linux, macOS, Windows)
name: onpc
description: Enhanced Music Controller

version: 2.14.3+314

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: 3.19.0

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.0
  quiver: ^3.0.1
  xml: ^6.5.0
  flutter_svg: ^2.0.9
  http: ^1.1.2
  draggable_scrollbar: ^0.1.0
  shared_preferences: ^2.0.5
  back_button_interceptor: ^5.0.0
  sprintf: ^6.0.0
  flutter_markdown: ^0.6.8
  url_launcher: ^6.3.1
  google_fonts: 6.1.0
  json_path: ^0.7.0
  syncfusion_flutter_sliders: ^23.1.36
  syncfusion_flutter_charts: ^23.1.36
  flutter_libserialport: ^0.4.0
  window_manager: ^0.3.7
  url_launcher_linux: 3.1.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  pedantic: ^1.4.0
  msix: 3.16.7

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/
    - lib/assets/buttons/
    - lib/assets/ri/
    - lib/assets/fonts/

msix_config:
  build_windows: false
  display_name: Enhanced Music Controller
  publisher_display_name: Mikhail Kulesh
  identity_name: XXX
  publisher: XXX
  msix_version: 2.14.3.0
  logo_path: windows\runner\resources\app_icon_512.png
  start_menu_icon_path: windows\runner\resources\app_icon_512.png
  tile_icon_path: windows\runner\resources\app_icon_512.png
  icons_background_color: '#0077dd'
  architecture: x64
  capabilities: 'internetClient'
  dont_install_cert: true
```
