### ISSUE TITLE
Error on Microsoft Store verification 

### ISSUE THREAD

**Issue by mjafartp** [YehudaKremer/msix#39]
### :information_source: Info
Version: `e.g. v2.0.0`

### :speech_balloon: Description
On Microsoft store verification getting below error 
"
App manifest resources tests

FAILED
Branding
Error Found: The branding validation test encountered the following errors:
Image file StoreLogo.backup.png is a default image.
Impact if not fixed: Microsoft Store apps are expected to be complete and fully functional. Apps using the default images e.g. from templates or SDK samples present a poor user experience and cannot be easily identified in the store catalog.

"
we are using 
`vs_generated_images_folder_path`

### :scroll: Pubspec.yaml

```yaml
msix_config:
  display_name: XXXX APP
  publisher_display_name: XXX XXX
  identity_name: XXXXX.XXX
  msix_version: 6.79.1.0
  certificate_path: C:\Apps\certs\xxx.pfx
  certificate_password: xxxxxxx
  publisher: CN=XXXXXX-XXXXXX-XXXXXX-XXXXXX-XXXXXXX
  vs_generated_images_folder_path: C:\Apps\Assets\icons
  icons_background_color: transparent
  architecture: x64
  capabilities: 'internetClient'

```
