### ISSUE TITLE
[BUG] The following restricted capabilities require approval before you can use them in your app: runFullTrust.

### ISSUE THREAD

**Issue by calcitem** [YehudaKremer/msix#44]
### :information_source: Info

v2.1.0

### :speech_balloon: Description

My program need no special permissions.

So I set capabilities: to `''`, and build:

```shell
flutter build windows
flutter pub run msix:create --store
```

And upload msix file to https://partner.microsoft.com to verify the msix file.

The result shows warnings:

```
The following restricted capabilities require approval before you can use them in your app: runFullTrust.
```

And Microsoft requied me to explain why I need this Restricted capabilities.

So how can I remove this warning? Thank you!

### :scroll: Pubspec.yaml

```
name: xxx
description: xxx

version: 1.0.4+1776

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  soundpool: ^2.0.0-nullsafety.0
  path_provider: ^2.0.1
  package_info_plus: ^1.0.1
  uuid: ^3.0.4
  url_launcher: ^6.0.3
  intl: 0.17.0
  animated_text_kit: ^4.1.1
  flutter_colorpicker: ^0.4.0
  catcher: ^0.6.6
  stack_trace: ^1.10.0
  device_info_plus_platform_interface: ^1.0.1
  devicelocale: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^2.1.0

flutter:
  generate: true
  uses-material-design: true

flutter_intl:
  enabled: true

msix_config:
  display_name: xxx
  publisher_display_name: xxx
  identity_name: xxx
  msix_version: 1.0.0.0
  publisher: CN=xxx
  capabilities: ''
  store: true
```
