### ISSUE TITLE
[BUG] How can I change the installation path?

### ISSUE THREAD

**Issue by samo92** [YehudaKremer/msix#47]
How can I change the installation path?

**Comment by YehudaKremer** [comment]
hello @samo92 

for now you cant,
but is a good feature to add in the future

**Comment by samo92** [comment]
Thank you !!!!!!!!

**Comment by sergiotucano** [comment]
Hi ! 
I trying use the output_path but this property only works for msix output directory, correct?
The installation folder, in Windows 10, is C:\Program Files\WindowsApps 

Do you have a method to change the installation folder ?

My config is: 

```
msix_config:
  display_name: PDVx Desk
  publisher_display_name: XXX
  identity_name: XXX
  anguages: pt-br
  msix_version: 1.0.0.0
  trim_logo: false
  logo_path: XXX
  certificate_path: XXX
  certificate_password: xxx
  output_path: C:\OUTPUT
  output_name: XXX
  build_windows: false
  app_installer:
    publish_folder_path: c:\OUTPUT
    hours_between_update_checks: 0
    automatic_background_task: true
    update_blocks_activation: true
    show_prompt: true
    force_update_from_any_version: false

```

Thx!
