### ISSUE TITLE
Error: SignerSign() failed." (-2147024885/0x8007000b)

### ISSUE THREAD

**Issue by Priyansu67** [YehudaKremer/msix#48]
v2.1.3

Description:
```
[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 90% signing..
The following certificate was selected:
    Issued to: www.priyansu.in
    Issued by: www.priyansu.in
    Expires:   Sat Jan 09 23:16:06 2049
    SHA1 hash: B106D3E8F020B4B167FA3AAEC17F4298DEBEC332

Done Adding Additional Store
Error information: "Error: SignerSign() failed." (-2147024885/0x8007000b)


SignTool Error: An unexpected internal error has occurred.
```

Pubspec.yaml:
```
msix_config:
  display_name: Headliners
  publisher_display_name: Priyansu Choudhury
  identity_name: www.priyansu.in
  msix_version: 1.0.0.0
  publisher: C = IN, S = Odisha, L = Jeypore, O = Priyansu Choudhury, OU = Personal, CN = www.priyansu.in
  certificate_path: C:\Users\priya\Desktop\CERTIFICATE.pfx
  certificate_password: somepassword
  icons_background_color: transparent
  architecture: x64
  capabilities: 'internetClient'
  store: false
```

My Certificate Subject:
`subject=C = IN, ST = Odisha, L = Jeypore, O = Priyansu Choudhury, OU = Personal, CN = www.priyansu.in, emailAddress = priyansuc67@gmail.com`
