### ISSUE TITLE
[BUG] Error in sign

### ISSUE THREAD

**Issue by ZaunSupremoXV** [YehudaKremer/msix#49]
### :information_source: Info

Version: `e.g. v2.1.3`

### :speech_balloon: Description

Error in run flutter pub run msix:create, return:
```
☑ parsing cli arguments
☑ validating config values
☑ cleaning temporary files
☑ creating app icons folder
☑ copying app icons
☑ copying VC libraries
☑ generate appx manifest
☑ generate PRI file
☑ packing
☑ cleaning temporary files
[❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚] 90% signing..


SignTool Error: No certificates were found that met all the given criteria.
```

### :scroll: Pubspec.yaml

```
dev_dependencies:
  flutter_test:
    sdk: flutter
  msix: ^2.1.3


msix_config:
  display_name: Desktop Example
  publisher_display_name: Erick
  identity_name: MyCompany.MySuite.MyApp
  msix_version: 1.0.0.0
  certificate_path: teste.pfx
  certificate_password: my_password
  publisher: CN=my_info, OU=my_info, OU=my_info, OU=my_info, OU=my_info, OU=my_info, L=my_info, S=my_info, C=my_info
```
