### ISSUE TITLE
[BUG] Installation failed

### ISSUE THREAD

**Issue by ggdream** [YehudaKremer/msix#56]
### :information_source: Info

Version: `e.g. v0.7.5`
v latest
### :speech_balloon: Description

Enter a description of your problem here
Hello, thank you very much for such a useful package. I have not been in contact with special windows development and learning, so I followed this document step by step, but after using the self-signed certificate provided by you to package, and the certificate has been imported into the system, clicking on the packaged installation package still cannot be installed. It prompts:

`This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted ( 0x800B010A)`.

If it is a certificate issued by myself, it can’t even be packaged, and there is an inaccurate error report. My yaml format is not wrong, but it prompts an error for the yaml format.

### :scroll: Pubspec.yaml

```yaml
msix_config:
  certificate_path: ./assets/test_certificate.pfx
  certificate_password: 1234
  publisher: CN=Msix Testing, O=Msix Testing Corporation, C=US
```
We ask that you include your pubspec.yaml file as a common problem we have seen has been the pubspec.yaml file being incorrect
