### ISSUE TITLE
[BUG] Icons-background-color always set to blue no matter what I set

### ISSUE THREAD

**Issue by Sangwan5688** [YehudaKremer/msix#69]
### :information_source: Info

Version: `v2.6.6`

### :speech_balloon: Description

As stated in the title itself, the `icon_background_color` is always shown `blue` (or whatever accent color is) in final built package, no matter what I write in config.

### :scroll: Pubspec.yaml

```
msix_config:
  display_name: BlackHole
  publisher_display_name: Ankit Sangwan
  identity_name: com.shadow.blackhole
  icons_background_color: transparent
  logo_path: assets/ic_launcher.png
  msix_version: 1.0.0.0
  # file_extension: .mp3, .m4a
```
