### ISSUE TITLE
[BUG] Msix-created app requires internet by default and works only when ran in administrator mode

### ISSUE THREAD

**Issue by claudiu-bele** [YehudaKremer/msix#72]
### :information_source: Info
Version: `2.7.3`

### :speech_balloon: Description

Msix created apps only run properly when ran in adminstrator mode. Any way to debug this? Feel like it might have something to do with my custom `sqlite3.dll` import not working if not in administrator mode. It works when ran straight from Android Studio though so i dunno(?)

### :scroll: Pubspec.yaml

```
name: immaterial_multiplat
description: The metaphysical suite for self-help, research and growth

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.9.0 # 3.9.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0  
  animated_stream_list: ^1.1.0
  flutter_svg: ^0.23.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

  # android, ios, web
  uuid: ^3.0.0
  # android, ios, web
  crypt: ^4.0.1

  moor: ^4.5.0
  sqlite3_flutter_libs: ^0.5.1
  path: ^1.8.0
  path_provider: ^2.0.4

  url_launcher: ^6.0.10

  # for desktop you need https://github.com/miguelpruivo/flutter_file_picker/wiki/Setup#desktop-go-flutter
  file_picker: ^4.2.4

  rxdart: ^0.27.2
  undo: ^1.3.1

  bloc: ^7.0.0
  flutter_bloc: ^7.0.0

  # toasts
  fluttertoast: ^8.0.3
  # graph view
  graphview: ^0.6.7

  flutter_colorpicker: ^0.3.5
  markdown_editable_textinput: ^2.0.2
  flutter_markdown: ^0.6.8

  #flutter build web --web-renderer canvaskit for web
  # https://stackoverflow.com/questions/64583461/how-to-use-skia-canvaskit-in-flutter-web

dev_dependencies:
  moor_generator: ^4.5.1
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  msix: ^2.7.3

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
    - assets/wallpapers/
    - assets/icons/
  generate: true
  uses-material-design: true

# flutter build windows
# flutter pub run msix:create
msix_config:
  display_name: ImmaterialAI
  publisher_display_name: FutureSoup
  identity_name: FutureSoup.Net.ImmaterialAI
  msix_version: 3.10.1.1
  logo_path: C:\Users\Claudiu\Documents\GitHub\Immaterial-Multiplat\package_with_release\web\icons\favicon.png
  assets_directory_path: C:\Users\Claudiu\Documents\GitHub\Immaterial-Multiplat\win_x64
  architecture: x64
  # capabilities: "internetClient,location,microphone,webcam"
```

**Comment by YehudaKremer** [comment]
Hello @claudiu-bele 
Is this problem appends also after running just the command `flutter build windows` (test the .exe file) ?

**Comment by claudiu-bele** [comment]
will try when i get home

**Comment by claudiu-bele** [comment]
It works on release 😎

I add these .dlls (first 3 to have flutter runtime, last standalone .dll) to the `build\windows\runner\Release` 
- `msvcp140.dll`
- `vcruntime140.dll`
- `vcruntime140_1.dll`
- `sqlite.dll`

**Comment by YehudaKremer** [comment]
But its still not working after installing with msix right ?

**Comment by claudiu-bele** [comment]
I'm not doing msix, why care about msix?

**Comment by claudiu-bele** [comment]
I'll try tho, sec

**Comment by claudiu-bele** [comment]
MSIX WORKS (+ `flutter build windows` and `hover build windows`) with `winx64` folder containing `.dll`s inside .exe's folder

Fix is obvious now, use double backslash when writing the path
```
DynamicLibrary _openOnWindows() {
  final corePath = 'win_x64\\sqlite3.dll';
  return DynamicLibrary.open(corePath);
}
```

## Msix setup

```
msix_config:
  display_name: ImmaterialAI
  publisher_display_name: FutureSoup
  identity_name: FutureSoup.Net.ImmaterialAI
  msix_version: 3.10.1.1
  logo_path: C:\Users\Claudiu\Documents\GitHub\Immaterial-Multiplat\package_with_release\web\icons\favicon.png
  assets_directory_path: C:\Users\Claudiu\Documents\GitHub\Immaterial-Multiplat\win_x64
  architecture: x64
  # capabilities: "internetClient,location,microphone,webcam"
```
