### ISSUE TITLE
[BUG]  App with sqlite3.dll, only works as admin

### ISSUE THREAD

**Issue by filipenanclarez** [YehudaKremer/msix#76]
### :information_source: Info

Version: `v2.8.1`
### :speech_balloon: Description

After `flutter build windows` i put sqlite3.dll on output folder. Then run `flutter pub run msix:create`.
Then make install with msix in a new clean computer.
In app folder `c:\program files\windowsapps\myapp` the sqlite3.dll is there, alright.
But if i run the app **_from start menu_**, app cannot load dll.
If i run **_from the folder_**, then app can load dll and works correctly. 
If i run **_from start menu as admin_**, then app can load dll and works correctly.
So i think problem is related with some permissions to run with capabilities to execute thirty party dlls, but i can't find in documentation.
I'm using `https://pub.dev/packages/sqflite_common_ffi` package, and if i run .exe from folder, with sqlite3.dll on same folder as .exe, work correctly. Only with msix instalation and then run from start menu as common user is problem.

### :scroll: Pubspec.yaml
```
name: xxxxxxxxx
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_windows: ^0.1.2
  webview_flutter: ^3.0.0
  flutter_vector_icons: ^1.0.0  
  sqflite: ^2.0.1
  path: ^1.8.0
  sqflite_common_ffi: ^2.1.0
  file_picker: ^4.3.1
  archive: ^3.1.6
  html: ^0.15.0  
  charset: ^0.2.0
  hive: ^2.0.5
  http: ^0.13.4
  path_provider: ^2.0.8
  xml: ^5.3.1
  url_launcher: ^6.0.17
  flutter_easyloading: ^3.0.3
  move_to_background: ^1.0.2
  cryptography: ^2.0.5
  share_plus: ^3.0.4
  bitsdojo_window: ^0.1.1+1  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons_maker: "^0.10.1"
  msix: ^2.8.1

flutter_icons:
  android: true
  ios: true
  windows: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  image_path_android: "assets/icon/android_icon.png"
  image_path_ios: "assets/icon/ios_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/nocover.png
    - assets/nocover.jpg
  fonts:
    - family: Roboto Mono
      fonts:
        - asset: assets/RobotoMono-Regular.ttf
    - family: M1
      fonts:
        - asset: assets/fonts/mplus-1m-regular.ttf
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/UbuntuMono-R.ttf

msix_config:
  display_name: XXXXX
  publisher_display_name: XXXX
  logo_path: "assets/icon/icon.png"
  ```
