### ISSUE TITLE
[BUG] VC Redis .dlls are not beeing copied 

### ISSUE THREAD

**Issue by rokk4** [YehudaKremer/msix#79]
### :information_source: Info

Version: `v2.8.4`

### :speech_balloon: Description

The VC .dlls are not getting copied.  I stumpled upon this by testing a released Store App on a freshly installed Win 10 VM ... fml...
Before the .dlls where always copied. I unpacked the .msix with the MSIX tool and could verify that no VC .dlls are included. :(

This seems to be a regression of #30 .  I can see that a test for this exists, so it seems very strange to me that this happens. I also verified that the VC libs are in the local msix plugin package.

BTW: Thank you very much for this package, it makes life much easier. 👍 

### :scroll: Pubspec.yaml
I use the --store flag to build for the store.

The configuration was working perfectly  up to 2.8.0 or maybe 2.8.2.

```yaml
msix_config:
  display_name: XXXXX®
  publisher_display_name: XXXX XXX XXXX
  identity_name:  XXXX.XXXXX
  msix_version: X.X.X.0
  publisher: CN=XXXXXXXXXXXXXXXXXXXXXXXXXX
  certificate_path: D:\XXXX\windows\msix\cert.pfx
  certificate_password: XXXXX
  logo_path: D:\XXXXXX\assets\icon\icon.png
  architecture: x64
  languages: "de-de"
  capabilities: 'internetClient'
```
