### ISSUE TITLE
[BUG] cant create installer

### ISSUE THREAD

**Issue by zezo357** [YehudaKremer/msix#91]
### :information_source: Info

Version: `2.8.16`

### :speech_balloon: Description
cant create installer
```
✓ parsing cli arguments
✓ validating config values
✓ cleaning temporary files
✓ creating app icons folder
✓ generating icons
✓ copying app icons
✓ copying VC libraries
✓ getting certificate publisher
✓ generate appx manifest
❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚❚ 64% generate package resource indexing files..
Microsoft (R) MakePRI Tool
Copyright (C) 2013 Microsoft. All rights reserved.


Usage:
------
    MakePri.exe new /pr <project root> /cf <config file> [options]

Example:
--------
    MakePri.exe new /pr C:\MyApp\src\ /cf C:\MyApp\priconfig.xml /mn
    C:\MyApp\AppXManifest.xml /of C:\MyApp\src\resources.pri /o

Description:
------------
    Creates a PRI file at [outputfile] by indexing all files in the
    [projectroot]and its subdirectories as directed by the [configxml]. The
    index will be assigned [indexname] to reference resources in the application

Required Parameters:
--------------------
    /ProjectRoot(pr)  : <FOLDERPATH> Root location of project files
    /ConfigXml(cf)    : <FILEPATH> Configuration file location. Use
                        'Makepri.exe createconfig' command to generate one

Options:
--------
    /OutputFile(of)   : <FILEPATH> Output location of PRI file, default is
                        [current directory]\resources.pri
    /Manifest(mn)     : <FILEPATH> Location of the application or component's
                        manifest. This parameter is ignored if [indexname]
                        is given. Default is [projectroot]\AppXManifest.xml
    /IndexName(in)    : <STRING> Name for the generated index of resources.
                        Typically matches the AppX package name, class library
                        simple name, etc. May be supplied via the
                        [manifest] parameter.
                        If IndexName is not specified and an AppX manifest
                        file is not present, the default name 'Application'
                        will be used.
    /VersionMajor(vma): <INTEGER> [Deprecated] Major version number for
                        index, default is 1
    /IndexLog(il)     : <FILEPATH> XML Log of indexed resources, no file
                        generated by default
    /AutoMerge(am)    : This flag is not recommended for normal use with AppX
                        packages. It causes Makepri.exe to set the auto
                        merge flag within the PRI file. Default is not set.
    /ReverseMap(rm)   : Generate a reverse mapping section in the PRI file
                        which can be used for debugging purposes.
    /MappingFile(mf)  : <MAPPINGFILETYPE> Generate a mapping file in the given
                        file format.
    /SchemaFile(sf)   : <FILEPATH> Output location of XML resource schema
                        description.
    /IndexOptions(io) : <OPTIONS> Options to provide detailed control over
                        behavior of resource indexers.
    /Overwrite(o)     : Overwrite an existing output file of the same name
                        without prompting
    /Verbose(v)       : Causes verbose messages to be output to the console
    /Help(h, ?)       : Display the usage help text
    /ExtensionDll(ex) : <FILEPATH> Location of the MRT environment extension
                        DLL. This DLL must be signed by a Microsoft-issued
                        certificate. Default is an empty path (no DLL
                        will be used).


    FOLDERPATH       - is a valid path to a folder
    FILEPATH         - is a path to a file, either relative to the current
                       directory or absolute
    MAPPINGFILETYPE  - Supported File type(s): 'AppX'



ERROR: PRI191: 0x80004005 - Appx manifest not found or is invalid. Please ensure well-formed manifest file is present. Or specify an index name with /in switch.
A name was started with an invalid character.


pub finished with exit code -1
```

### :scroll: Pubspec.yaml

```
version: 3.0.178+1


environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  catcher: ^0.6.6
  sqflite: ^2.0.0+3
  async: ^2.6.1
  win32: ^2.2.9
  xpath_selector: ^2.2.2
  cryptography: ^2.0.5
  #video player
  volume_controller: ^2.0.2

  shared_preferences: ^2.0.13

    #flutter_vlc_player:
  #vlc_flutter:
    #git: https://github.com/zezo357/vlc-flutter
  video_player: ^2.2.18
  auto_orientation: ^2.0.2
  screen_brightness: ^0.1.1
  flutter_meedu: ^5.0.0
  flutter_spinkit: ^5.0.0
  meta: ^1.3.0
  dart_vlc: ^0.1.7
  share_plus: ^3.0.4

  window_manager: ^0.1.1
  screen_retriever: ^0.1.0
  oktoast: ^3.1.3+1

  #end of video player
  flutter_screenutil: "5.0.2"
  connectivity_plus: ^2.0.1
  path: ^1.8.0
  cached_network_image: ^3.0.0
  wakelock: ^0.6.1
  retry: ^3.1.0
  version: ^2.0.0
  permission_handler: ^8.1.1
  filesize: ^2.0.1
  fluttertoast: ^8.0.7
  helpers: ^1.1.3
  dio: ^4.0.0
  flutter_local_notifications: ^9.0.0
  queue: ^3.1.0
  hotkey_manager: ^0.1.2
  archive: ^3.1.6

  android_intent: ^2.0.2
  device_apps: ^2.1.1
  html: ^0.15.0
  file_picker: ^4.0.0
  workmanager: ^0.5.0-dev.8

  pull_to_refresh: ^2.0.0
  encrypt: ^5.0.0
  draggable_scrollbar: ^0.1.0
  auto_size_text: ^3.0.0-nullsafety.0
  intl: ^0.17.0
  fluttericon:
  android_path_provider: ^0.3.0
  open_file:
  collection: ^1.15.0-nullsafety.4
  liquid_progress_indicator: ^0.4.0
  menu_button: ^1.4.2+1
  sqflite_common_ffi:
  xml: ^5.3.1
  google_nav_bar: ^5.0.5

  #flutter_webview_plugin:
    #git: https://github.com/zezo357/flutter_webview_plugin

dev_dependencies:
  flutter_native_splash: ^2.0.1+1
  flutter_launcher_icons: ^0.9.0
  #msix: ^3.0.0-dev.1
  msix: ^2.8.16


  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  windows: true
  ios: true
  image_path: "assets/icon.png"

msix_config:
  display_name: AnimeHere
  publisher_display_name: abdelaziz
  identity_name: com.zcreations.AnimeHere
  msix_version: 1.0.0.0
  logo_path:  G:\My Work HDD2\AndroidStudioProjects\anime_here\windows\runner\resources\app_icon.ico
  start_menu_icon_path: G:\My Work HDD2\AndroidStudioProjects\anime_here\windows\runner\resources\app_icon.ico
  tile_icon_path: G:\My Work HDD2\AndroidStudioProjects\anime_here\windows\runner\resources\app_icon.ico


```
