### ISSUE TITLE
[FEATURE REQUEST] comServer+toastNotificationActivation support

### ISSUE THREAD

**Issue by azchohfi** [YehudaKremer/msix#94]
### :speech_balloon: Description
If your app is using toast notifications, your manifest needs to define a comServer extension, as well as a toastNotificationActivation extension, given a specific CLSID (https://docs.microsoft.com/en-us/windows/apps/design/shell/tiles-and-notifications/send-local-toast-desktop-cpp-wrl#msixsparse-package). There is no way to specify such things in the cli, nor in the pubspec.yaml.

### :question: Platform
Windows

**Comment by azchohfi** [comment]
I think I'll send a PR to support these things.

**Comment by YehudaKremer** [comment]
Hello @azchohfi 

I'm currently working on adding [App Installer](https://docs.microsoft.com/en-us/windows/msix/app-installer/app-installer-file-overview) (updates outside of the Microsoft store) in this [branch](https://github.com/YehudaKremer/msix/tree/app-installer),
after that, i will be glad to add this nice feature.

You more then welcome to add features to this package 👍 
if you do, please make branch from 3.0v (not the main branch).

how we can implement this toast feature in the yaml file?
you can do something similar to what I'm planning for the AppInstaller feature, see this [code](https://github.com/YehudaKremer/msix/blob/c4966bd2c171cf6e0de62ce8518ff0a1506e37d0/lib/src/configuration.dart#L108-L128), then the yaml will look like this:
```yaml
msix_config:
  display_name: MyApp
  publisher_display_name: MyApp
  app_installer:
    publish_folder_path: C:/some/path
    installer_path: C:/some/path2
    show-prompt: true
  identity_name: de.myapp2.test
  msix_version: 1.0.3.0
```
